<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{Данные по 1 машине}</title>
    <link href="style.css" rel="stylesheet" type="text/css">
    <title>Каталог автомобилей</title>
</head>
<body>
<div id="content" style="width: 800px; margin: 0 auto;">
    <h1>Общий Каталог Автомобилей</h1>
    <font size="5">
        <form action="https://yandex.ru">
            <label>Пойск других автомобилей
                <input type="text" name="q" placeholder="Ваш запрос">
            </label>
            <input type="submit" value="Поиск!">
        </form>
        <a href="http://localhost:8080/Login" title="Вернуться в общий каталог">Выйти из учётной записи</a>
    </font>
    <br>
    <br>
    <br>
    <img src="https://91.img.avito.st/image/1/vgsC_7a_EuJ0WuDkcqm-ap5cFOi8nBYQsFwQ5LpaEOK2Gg" align="top" vspace="10"
         border="3" alt="">
    <br>
    <font size="5">
        <tr>Ford Focus -</tr>
        <a href="http://localhost:8080/CarStore/1" title="Полная информация по 1 автомобилю">1 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://www.autosite.ua/img/models/17/foto_002.jpg" align="top" vspace="10" border="3" alt="">
    <br>
    <font size="5">
        <tr>Mitsubishi Lanser X -</tr>
        <a href="http://localhost:8080/CarStore/2" title="Полная информация по 2 автомобилю">2 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://i.ytimg.com/vi/Oog9_Rspuu0/hqdefault.jpg" align="top" vspace="10" border="3" alt="">
    <br>
    <font size="5">
        <tr>Subaru Impreza I -</tr>
        <a href="http://localhost:8080/CarStore/3" title="Полная информация по 3 автомобилю">3 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://www1.garaget.org/archive/129/128351/220364/220364-2104217.jpg" align="top" vspace="10" border="3"
         alt="">
    <br>
    <font size="5">
        <tr>Nissan Skyline X R34 -</tr>
        <a href="http://localhost:8080/CarStore/4" title="Полная информация по 4 автомобилю">4 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://a.d-cd.net/d0fdd72s-480.jpg" align="top" vspace="10" border="3" alt="">
    <br>
    <font size="5">
        <tr>Honda Civic VI -</tr>
        <a href="http://localhost:8080/CarStore/5" title="Полная информация по 5 автомобилю">5 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://s.auto.drom.ru/photo/KA37MZHLFoaffj6AcP51b1Vt-riTS0QbNPlEWMCn6fSiGF7kfQDq4MUWiam3m-gcmTqBgiBNsgocBQn8046wZ7hwuoknYg.jpg"
         align="top" vspace="10" border="3" alt="">
    <br>
    <font size="5">
        <tr>Nissan Silvia VII -</tr>
        <a href="http://localhost:8080/CarStore/6" title="Полная информация по 6 автомобилю">6 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://www.geilekarre.de/upload/karre/2055763.jpg" align="top" vspace="10" border="3" alt="">
    <br>
    <font size="5">
        <tr>Acura Integra III -</tr>
        <a href="http://localhost:8080/CarStore/7" title="Полная информация по 7 автомобилю">7 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://a.d-cd.net/dd53388s-480.jpg" align="top" vspace="10" border="3" alt="">
    <br>
    <font size="5">
        <tr>Mitsubishi Eclipse III -</tr>
        <a href="http://localhost:8080/CarStore/8" title="Полная информация по 8 автомобилю">8 автомобиль</a>
    </font>
    <br>
    <br>
    <br>

    <img src="https://90.img.avito.st/image/1/6xgun7aBR_FYOrX3dNSDcNc8Q_eMPEf3619D91g6tfeYOEv1mD5HtQ" align="top"
         vspace="10" border="3" alt="">
    <br>
    <font size="5">
        <tr>Volkswagen Golf GTI IV -</tr>
        <a href="http://localhost:8080/CarStore/9" title="Полная информация по 9 автомобилю">9 автомобиль</a>
    </font>
    <br>
    <br>
    <br>
</div>
</body>
</html>